<?php
return array (
  'ZC_SITE_TURNOFF' => false,
  'ZC_DATABASE_TYPE' => 'mysql',
  'ZC_SQLITE_NAME' => '',
  'ZC_SQLITE_PRE' => 'zbp_',
  'ZC_MYSQL_SERVER' =>'localhost',
  'ZC_MYSQL_USERNAME' => 'root',
  'ZC_MYSQL_PASSWORD' => 'root',
  'ZC_MYSQL_NAME' => 'zblog',
  'ZC_MYSQL_CHARSET' => 'utf8',
  'ZC_MYSQL_PRE' => 'zbp_',
  'ZC_MYSQL_ENGINE' => 'MyISAM',
  'ZC_MYSQL_PORT' => '3306',
  'ZC_MYSQL_PERSISTENT' => false,
  'ZC_PGSQL_SERVER' => SAE_MYSQL_HOST_M,
  'ZC_PGSQL_USERNAME' => 'postgres',
  'ZC_PGSQL_PASSWORD' => '',
  'ZC_PGSQL_NAME' => '',
  'ZC_PGSQL_CHARSET' => 'utf8',
  'ZC_PGSQL_PRE' => 'zbp_',
  'ZC_PGSQL_PORT' => '5432',
  'ZC_PGSQL_PERSISTENT' => false,
  'ZC_YUN_SITE' => '',
)
?>
